#!/bin/bash
echo "=========================================="
echo "  MONOREPO AUDIT REPORT"
echo "  247GBS Affiliates - Frontend + Backend"
echo "=========================================="
echo ""
echo "Generated: $(date)"
echo ""

echo "=== 1. MOCK DATA AUDIT ==="
echo "Status: CLEAN"
echo "- No mock data found in frontend source"
echo "- No MSW (Mock Service Worker) detected"
echo "- No hardcoded test/fake data arrays"
echo "- Only UI placeholders (input placeholders) found - these are legitimate"
echo ""

echo "=== 2. API ENDPOINT AUDIT ==="
echo "Status: CRITICAL - MISSING ENDPOINTS"
echo ""
echo "Missing backend endpoints (frontend calls these):"
echo "  ❌ GET  /api/v1/account-manager/dashboard/revenue  (useAccountManagerRevenue)"
echo "  ❌ GET  /api/v1/admin/dashboard/stats               (useAdminStats)"
echo "  ❌ GET  /api/v1/admin/users                         (useAdminUsers)"
echo "  ❌ PATCH /api/v1/admin/users/:id/status            (useAdminUsers)"
echo "  ❌ GET  /api/v1/learning                            (useLearningResources)"
echo "  ❌ GET  /api/v1/users/agents                        (useAgents)"
echo ""
echo "Frontend calls that WORK (matching backend):"
echo "  ✅ Auth: login, register, profile"
echo "  ✅ Skills: GET /skills"
echo "  ✅ Assessment: GET /quiz, POST /submit"
echo "  ✅ Tasks: GET /tasks, POST /tasks, POST /:id/accept"
echo "  ✅ Wallet: GET /wallet, GET /transactions, POST /withdraw"
echo "  ✅ Messaging: conversations, messages, send"
echo "  ✅ Profile: PATCH /users/me"
echo ""
echo "Backend-only endpoints (not used by frontend):"
echo "  - POST /auth/register/admin"
echo "  - POST /wallet/deposit"
echo "  - POST /tasks/incoming (webhook)"
echo "  - POST /tasks/:id/assign, :id/decline, PATCH :id/status"
echo "  - POST /assessment/questions (admin)"
echo "  - Verification CRUD (admin)"
echo "  - Categories/Sectors CRUD (admin)"
echo ""

echo "=== 3. N+1 QUERY AUDIT ==="
echo "Status: WARNING - POTENTIAL ISSUES FOUND"
echo ""
echo "Potential N+1 queries identified:"
echo "  ⚠️  assessment.service.ts: submitQuiz() - loops through answers calling findOne() per question"
echo "      Fix: Use findBy({ id: In(questionIds) }) to fetch all in one query"
echo ""
echo "  ⚠️  messaging.service.ts: getMyConversations() - returns conversations but no participant details"
echo "      Frontend likely needs participant names/avatars -> would trigger N+1 if fetched per conversation"
echo "      Fix: Add participant relations or denormalize participant data"
echo ""
echo "  ✅ tasks.service.ts: Uses relations in findAll/findOne (client, assignedAgent)"
echo "  ✅ sectors.service.ts: Uses relations for categories"
echo "  ✅ categories.service.ts: Uses relations for children"
echo "  ✅ wallet.service.ts: Efficient queries"
echo "  ✅ verification.service.ts: Efficient queries"
echo ""

echo "=== 4. OTHER ISSUES ==="
echo ""
echo "  ⚠️  Messaging: Conversation entity stores participantIds as simple-array (no FK relation)"
echo "      Makes querying participants inefficient"
echo ""
echo "  ⚠️  Auth: Frontend decodes JWT manually to get user info (in useAuth.ts)"
echo "      Should use /auth/profile endpoint instead"
echo ""
echo "  ⚠️  Base URL mismatch: Frontend apiClient defaults to localhost:3000"
echo "      Backend runs on :3000 with prefix /api/v1"
echo "      Should use NEXT_PUBLIC_API_URL=http://localhost:3000/api/v1"
echo ""

echo "=== RECOMMENDATIONS (Priority Order) ==="
echo "1. CRITICAL: Implement missing backend endpoints (6 endpoints)"
echo "2. HIGH: Fix N+1 in assessment.service.ts submitQuiz()"
echo "3. HIGH: Fix messaging participant loading (add user relation or denormalize)"
echo "4. MEDIUM: Add /users/agents endpoint to users controller"
echo "5. MEDIUM: Update apiClient baseURL to include /api/v1"
echo "6. LOW: Add admin dashboard controller"
echo ""

echo "=========================================="
